# -*- coding: utf-8 -*-
"""atribuiocoes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4rLvxuf4hRFZQb8HFbp98L7-vQEJW1Y
"""

!python teste.py

#Atribuindo valores usando condicoes

numero = int(input("Digite um numero: "))

if(numero < 10):
  mensagem = "Menor que 10"
else:
  mensagem = "Nao e menor que 10"

print(mensagem)

# Atribuicao condicional

numero = int(input("Digite um numero: "))

mensagem = "Menor que 10" if(numero < 10) else "Nao e menor que 10"

print(mensagem)

venda = float(input("Digite o valor da venda: "))

if(venda > 1000):
  desconto = venda * 0.10
else:
  desconto = 0

venda_final = venda - desconto
print("Venda: ",venda)
print("Desconto:",round(desconto,2))
print("Venda final: ",venda_final)

#@title teste
# Venda utilizando atribuicao condicional
venda = float(input("Digite o valor da venda: "))

desconto = venda * 0.10 if(venda > 1000) else 0

venda_final = venda - desconto
print("Venda:",venda)
print("Desconto:",round(desconto,2))
print("Venda final:",venda_final)

#@title Calulo IMC

altura = float(input("Digite a sua altura: "))
peso = float(input("Digite o seu peso: "))

imc = peso / (altura ** 2)

if(imc < 18.5):
  print("Abaixo do peso",imc)
elif(imc >=18.5 and imc <=24.9):
  print("Peso normal")
elif(imc>=25 and imc<=29.9):
  print("Sobrepeso")
elif(imc>=30 and imc <=34.9):
  print("Obesidade grau 1")
elif(imc>=35 and imc >=39,9):
  print("Obesidade grau 2")
elif(imc>=40):
  print("Obesidade grau 3")