# -*- coding: utf-8 -*-
"""atividade 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Bg_f2w_8b1bd2wpgwH_G8WZ7lXnPROa
"""

idade = int(input("Digite a sua idade: "))

batimentos = (86400 * 365)* idade
print()
print("Esta e a quantidade de batimentos",batimentos)