# -*- coding: utf-8 -*-
"""atividade 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rc81lDF6LtZpi_f789P7pRLtzVUmH0bu
"""

nome1 = (input("Digite o nome da pessoa 1: "))
nome2 = (input("Digite o nome da pessoa 2: "))
nome3 = (input("Digite o nome da pessoa 3: "))
print()
idade1 = int(input("Digite a idade da pessoa 1: "))
idade2 = int(input("Digite a idade da pessoa 2: "))
idade3 = int(input("Digite a idade da pessoa 3: "))
print()
peso1 = float(input("Digite o peso da pessoa 1: "))
peso2 = float(input("Digite o peso da pessoa 2: "))
peso3 = float(input("Digite o peso da pessoa 3: "))

print()
print("O nome, idade e peso da pessoa 1 sao: ",nome1,"/",idade1,"/",peso1)
print()
print("O nome, idade e peso da pessoa 2 sao: ",nome2,"/",idade2,"/",peso2)
print()
print("O nome, idade e peso da pessoa 3 sao: ",nome3,"/",idade3,"/",peso3)
print()

media_peso = (peso1 + peso2 + peso3)/3
peso_arredondado = round(media_peso,2)

print("A media aritmetica do peso das 3 pessoas e: ",peso_arredondado)