# -*- coding: utf-8 -*-
"""Atividade3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_7G_NTDZLeZWAi4H7xJlaNgAriHzhq-
"""

identificacao = int(input("Digite a identificacao do vendedor: "))
print()
salario = float(input("Digite o salario fixo do vendedor:"))
print()
vendas = float(input("Digite o total de vendas efetuadas pelo vendedor: "))
print()
percentual = float(input("Digite o percentual de comissado do vendedor:"))
print()

percentual_vend = percentual / 100

comissao = vendas * percentual_vend
salario_total = salario + comissao

print("O vendedor",identificacao,"Com salario fixo de",salario)
print()
print("Teve um total de comissao",comissao)
print()
print("Totalizando seu salario final:",salario_total)