# -*- coding: utf-8 -*-
"""Entrada_de_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16SzihC89gFyA8OlbyG_HLChXdMoj48-x
"""

print('Wake up neo\n')
print('The matrix has you...')

meu_nome = "Vitor"
minha_idade = 24
meu_salario = 2000.99
estou_de_ferias = False

print(meu_nome)
print(minha_idade)
print(meu_salario)
print(estou_de_ferias)

print(type(meu_nome))
print(type(minha_idade))
print(type(meu_salario))
print(type(estou_de_ferias))

#entrada de dados

nome = input("Digite seu nome: ")
idade = input("Digite sua idade: ")
salario = input("Digite seu salario: ")
print()
print(nome)
print(idade)
print(salario)

print("nome",nome,"idade",idade)

num1 = int(input('Digite o primeiro numero: '))
num2 = int(input('Digite o segundo numero: '))

resultado = num1 + num2

print(resultado)

num1 = 50
num2 = 20
print("O primeiro numero e",num1,"e o segundo e",num2)