# -*- coding: utf-8 -*-
"""est_cond2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaoADvp6Qf2ldU4_6EhiGymlgO0Ue0Yh
"""

idade = int(input("Digite a sua idade para ser se precisara votar: "))

if (idade >= 18 and idade <= 65):
  print()
  print("Nao e obrigatorio a votacao")

elif idade == 16:
  print()
  print("Sua votacao e opcional")

else:
  print()
  print("e obrigatorio a votacao")

nota = int(input("Digite a nota do aluno: "))
presenca = int(input("Digite a presenca do aluno: "))

if (nota < 50 or presenca < 75):
  print("Aluno reprovado")
else:
  print("Aluno aprovado ")

curso = input("Digite seu curso: ")
ano = int(input("Digte o ano de inicio: "))
dia = input("Digite o dia que faz aula: ")

if (curso == "python" and ano == 2025 and dia == "sabado"):
  print()
  print("Bem vindo!!!")

else:
  print()
  print("Sala errada")

print("1. Idoso")
print("2. Gestante")
print("3. Cadeirante")
print("4. Outros")

resposta = int(input("Digite uma opcao: "))

if (resposta == 1 or resposta == 2 or resposta == 3):
  print()
  print("Voce tem direito a fila prioritaria")
elif resposta > 4:
  print()
  print("Digite uma opcao valida")
else:
  print()
  print("Voce nao tem direito")

num1 = int(input("Digite o primeiro numero: "))
num2 = int(input("Digite o segundo numero: "))
num3 = int(input("Digite o terceiro numero: "))

numeros = [num1, num2, num3]

numeros.sort()

print(numeros)

num1 = int(input("Digite o primeiro numero: "))
num2 = int(input("Digite o segundo numero: "))
num3 = int(input("Digite o terceiro numero: "))

if(num1 < num2 and num1 < num3 and num2 < num3):
  print(num1,num2,num3)

elif(num1 < num2 and num1 < num3 and num3 < num2):
  print(num1,num3,num2)

elif(num2 < num1 and num2 < num3 and num1 < num3):
  print(num2,num1,num3)

elif(num2 < num1 and num2 < num3 and num3 < num1):
  print(num2,num3,num1)

elif(num3 < num1 and num3 < num2 and num2 < num1):
  print(num3,num2,num1)

elif(num3 < num1 and num3 < num2 and num1 < num2):
  print(num3,num1,num2)

dia = int(input("Digite um numero da semana 1~7: "))

if dia > 7 or dia < 1:
  print("Digite um dia valido")

elif dia == 1:
  print("Domingo")
elif dia == 2:
  print("Segunda")
elif dia == 3:
  print("Terca")
elif dia == 4:
  print("Quarta")
elif dia == 5:
  print("Quinta")
elif dia == 6:
  print("Sexta")
elif dia == 7:
  print("Sabado")

numero = int(input("Digite um numero da semana 1~7: "))

match numero:
  case 1:
    print("Domingo")
  case 2:
    print("Segunda")
  case 3:
    print("Terca")
  case 4:
    print("Quarta")
  case 5:
    print("Quinta")
  case 6:
    print("Sexta")
  case 7:
    print("Sabado")
  case _:
    print("Numero invalido")