# -*- coding: utf-8 -*-
"""est_decisao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4WXU5lnBS5tKjRBdO9t-OGAYxns9_su
"""

num = int(input("Digite um numero: "))
print()
if num > 10:
  print("O numero e maior que 10")
if num == 10:
  print("O numero e igual a 10")
if num < 10:
  print("O numero e menor que 10")

#if e else

n = int(input("Digite um numero: "))

if n > 10:
  print("E maior que 10")
elif n < 10:
    print("Menor que 10")
else:
    print("Igual a 10")

# 14.00 pontual
# < 14.00 adiantado
# > 14.00 atrasado

horario = float(input("Digite o horario de chegada: "))

if horario == 14.00:
  print("Pontual")

elif horario < 14.00:
    print("Adiantado")
elif horario < 14.30:
    print("atrasado pode entrar")
elif horario > 14.30:
    print("atrasado falta na aula")

num1 = int(input("Digite o primeiro numero: "))
num2 = int(input("Digite o segundo numero: "))

soma = num1 + num2

if soma > 10:
  print(soma)

num = float(input("Digite um numero: "))

if num > 20:
  maior = num/2
  print(maior)
else:
  print("Erro no numero digitado")

num1 = int(input("Digite o primeiro numero: "))
num2 = int(input("Digite o segundo numero: "))


if num1 > num2:
  print(num2,num1)
else:
  print(num1,num2)

num = int(input("Digite um numero: "))

if num > 20:
  print("Maior que 20")
elif num < 20:
  print("Menor que 20")
else:
  print("Igual a 20")

ano_nasc = int(input("Digite o ano de nascimento: "))

ano_atual = 2025
calcula = ano_atual - ano_nasc

if ano_nasc > 2025:
  print("Ano incorreto, maior que o ano atual")

elif calcula > 150:
  print("Idade maior que o permitido no cadastro:",calcula)

elif calcula > 25:
    print(calcula)