# -*- coding: utf-8 -*-
"""BasicoRepeticao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-A1z8Q_xDhRqnEtu1y9vcd-LuDRSMDd3
"""

c = 0
nota = 0
lista = []
totalnota = 0
contador = 0

while c < 4:
  nota = int(input(f"Digite a nota do aluno {contador + 1}: "))
  lista.append(nota)
  contador += 1
  totalnota += nota

  c = c + 1

media = totalnota / contador

c = 0
while c < 4:
  if lista[nota] < 6:
    print("Alunos abaixo da media: ")
    print(lista[c])
    c = c + 1
print("A media da turma e: ", media)