# -*- coding: utf-8 -*-
"""EstruturaWhile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AC_t9IZVBulfocIdxH_HmSQ1RA2jnp_s
"""

#@title estrutura while

conta = -100
while conta < 0:
    print("Em debito")
    print("Aumentando 10")
    conta = conta + 10
    print("Conta: ",conta)
if(conta==0):
    while conta < 1000:
      conta = conta + 100
      print("Aumentando 100")
      print("Conta: ",conta)

contador = 0

while contador < 10:
  contador = contador + 1
  print(contador)
if contador == 10:
  while contador == 10 and:
    contador = contador - 1
  print(contador)