# -*- coding: utf-8 -*-
"""aula_dia22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15HX_0Tq7ukfjMUXPsv5eXB1opvFOKCbg
"""

c = 0
while c <=100:
  if c == 25:
    print("Voce chegou no 25")
  else:
    print(c)

  c = c + 1

if c != 25:
  print(c)
else:
  print("Voce chegou no 25")

c = 1
while c <= 100:
  print(c)
  if c == 27:
    break
  c = c + 1

c = 0

while c <= 100:
  if c != 40 and c != 80:
    print(c)
  c = c + 10

c = 1

while c <= 100:
  if c < 50 or c > 59:
    print(c)
  c = c + 1

c = 1

while c <= 100:
  if c >= 50 and c <= 59:
    pass
  else:
    print(c)
  c = c + 1

op = ''

while op != 's':
  op = input("Digite um letra ou digite s para parar: ")

print("Programa finalizados")

contador = 0
soma_salarios = 0

while contador < 4:
  salario = float(input(f"Digite o salario do funcionario{contador + 1}: "))
  soma_salarios += salario
  contador += 1

print(f"A soma dos salarios e: R${soma_salarios:.2f}")

fun1 = ''
fun2 = ''
fun3 = ''
fun4 = ''

while fun1 == '' and fun2 == '' and fun3 == '' and fun4 == '':
  fun1 = float(input("Digite o salario do fun1:"))
  fun2 = float(input("Digite o salario do fun2:"))
  fun3 = float(input("Digite o salario do fun3:"))
  fun4 = float(input("Digite o salario do fun4:"))

  soma = fun1 + fun2 + fun3 + fun4
print("A soma dos salarios e R$",soma)

c = 0
total_salario = 0

while c < 4:
  salario = float(input("Digite o salario: "))
  total_salario = total_salario + salario
  c = c + 1

print(total_salario)

alunos = int(input("Digite a quantidade de alunos: "))
qtd_alunos = 0
total_notas = 0

while qtd_alunos < alunos:
    notas = float(input(f"Digite a nota do aluno{qtd_alunos + 1}: "))
    if notas > 10 or notas < 0:
      print("A nota nao pode ser maior que 10")
    else:
      total_notas += notas
      qtd_alunos += 1
      media = total_notas / qtd_alunos

print(f"A media total da sala e: {media:.1f}")

n_alunos = int(input("Digite a quantida de alunos: "))
c = 0
soma_nota = 0


while c < n_alunos:
  nota = float(input("Digite as nota do aluno: "))
  soma_nota = soma_nota + nota
  c = c + 1

media = soma_nota / n_alunos
print("A media da turma e:",media)

num = 0
c = 0
maior = 0

while c < 6:
  num = int(input("Digite um numero: "))
  if num > maior:
    maior = num

  c = c + 1
print(maior)