# -*- coding: utf-8 -*-
"""Aula_10_05_25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1szce8D0lTE8ZJrkyRXBshnWKMwhmgh8U
"""

# dicionario

di1 = {"Nome":"Vitor",
          "Sobrenome":"Boarreto",
          "Idade":24,
          "Cursos":["Eng computacao", "Python","Arduino"]
          }

print(di1)
print(di1['Nome'])
print(di1['Sobrenome'])
print(di1['Idade'])
print(di1['Cursos'])
print(di1['Cursos'][0])
print("--------")
print("*Cursos*")
print("--------")
for curso in  di1['Cursos']:
  print(curso)

# Preenchimento do dicionario

di2 = {}
di2['nome'] = input("Digite um nome: ")
di2['sobrenome'] = input("Digite o sobrenome: ")
di2['idade'] = int(input("Digite a idade: "))

print(di2)
print(di2['nome'])
print(di2['sobrenome'])
print(di2['idade'])

#Usando in para verificar chaves
if 'nome' in di1:
  print("Chave já cadastrada")
else:
  di1['nome'] = input("Digite um nome: ")

print('nome' in di1)
print('nome' in di1 and 'Altura' in di1)
print(di1)

# Acessando valores

print(di1['nome'])

if 'alura' in di1:
  print(di1['altura'])
else:
  di1['altura'] = float(input("Digite a altura: "))
print(di1)

# Adicionando listas ao dicionario

if 'courses' not in di1:
  di1['courses'] = []

n_cursos = int(input("Quantos quer adicionar? "))

c = 0
while c < n_cursos:
  course = input("Digite o nome do curso: ")
  di1['courses'].append(course)
  c = c + 1

print(di1)

# mostrando chaves e valores
print("----------------")
print("Mostrando chaves")
print("----------------")

for c in di1:
  print(c)
print()
print("-----------------")
print("Mostrando valores")
print("-----------------")

for v in di1.values():
  print(v)
print()
print("--------------------------")
print("Mostrando chaves e valores")
print("--------------------------")
for c in di1:
  print(c,'-',di1[c])

#chave dinamica

chave = 'sobrenome'

print(di1[chave])

#tipos de chave

dd = {"basica":"Vlor basico"}
print(dd["basica"])

# percorrendo um texto

texto = 'Braganca'

print(len(texto))
print(texto[0])

for letra in texto:
  print(letra)

aluno1 = {"nome":"vitor","idade":24,"curso":"python"}
aluno2 = {"nome2":"alberto","idade2":25,"curso":"python"}
aluno3 = {"nome3":"boarreto","idade3":26,"curso":"python"}

lista = []

lista.append(aluno1)
lista.append(aluno2)
lista.append(aluno3)

print(aluno1)
print(aluno2)
print(aluno3)
print(lista)

pessoas = []

c = 0

while c < 1:
  pessoa = {}
  pessoa['cpf'] = input("Digite o CPF: ")
  pessoa['nome'] = input("Digite o nome: ")
  pessoa['idade'] = input("Digite a idade: ")
  pessoa['telefone'] = input("Digite o telefone: ")

  pessoas.append(pessoa)

  c = c + 1
print()
for pessoa in pessoas:
  print("CPF:",pessoa['cpf'])
  print("Nome:",pessoa['nome'])
  print("Idade:",pessoa['idade'])
  print("Telefone:",pessoa['telefone'])

dic = {}
palavra = input("Digite a palavra: ")

for l in palavra:
 if l not in dic:
  dic[l] = 1
 else:
  dic[l] = dic[l] + 1

print(dic)

lista = []


c = 0

while c < 3:
  pessoa = {"nome":"sobrenome":"","rg":"","idade",-1}
  pessoa["nome"] = input("Digite o nome: ")
  pessoa["sobrenome"] = input("Digite o sobrenome: ")
  pessoa["rg"] = input("Digite o RG: ")
  pessoa["idade"] = int(input("Digite a idade: "))
  lista.append[pessoa]

  c = c + 1

for pessoa in lista:
  print("Nome: ",pessoa["nome"])
  print("Sobrenome: ",pessoa["sobrenome"])
  print("RG: ",pessoa["rg"])
  print("Idade: ",pessoa["idade"])

#estoque
opcao = ''
lista_prod = []
while opcao != 0:
  #menu de opcoes
  print("Menu de opcoes:")
  print("1 - Adicionar produto")
  print("2 - Remover produto")
  print("3 - Exibir estoque ")
  print("0 - Sair")
  opcao = int(input("Digite a opcao desejada: "))
  #verificao de erro
  if opcao > 3 or opcao < 0:
    print()
    print("--------------")
    print("Opcao invalida")
    print("--------------")
    print()
  #finalizador
  elif opcao == 0:
    print()
    print("***Programa finalizado***")
  #adiciona produto
  elif opcao == 1:
    produtos = {"nome":"","quantidade":""}
    produtos["nome"] = input("Cadastre o nome do produto: ")
    produtos["quantidade"] = float(input("Digite a quantidade: "))

    lista_prod.append(produtos)
  #exclui produto
  elif opcao == 2:
    del(produtos)
  #mostra os produtos
  elif opcao == 3:
    for produtos in lista_prod:
       print("Produto: ",produtos["nome"])
       print("Quantidade: ",produtos["quantidade"])

opcao = ''
estoque = []
while opcao != 4 or opcao < 1 or opcao > 4:

  print("Menu de opcoes:")
  print("1 - Adicionar produto")
  print("2 - Remover produto")
  print("3 - Exibir estoque ")
  print("4 - Sair")
  opcao = int(input("Digite a opcao desejada: "))

  if opcao ==1:
    produto = input("Nome do produto")
    quantidade = int(input("Quantidade no estoque: "))
    estoque[produto] = quantidade

  elif opcao == 2:
    for produto, quantidade in estoque.items():
      quantidade = input(produto,":",quantidade)

      produto = input("Nome do produto a remover: ")
      quantidade = input("Quantidade a remover")

      estoque[produto] = estoque[produto] - quantidade
      if estoque[produto] < 1:
        del(estoque[produto])
  elif opcao == 3:
    print("Relatorio")
    for produto, quantidade in estoque.items():
      print(produto,":",quantidade)
  elif opcao == 4:
    print("Saindo do sistema")

#lista de dicionarios

lista10 = []
lista.append({"nome":"Vitor"})

print(lista10[0]["nome"])

c = 0

while c < 2:
  nome = input("Digite o seu nome: ")
  lista.append({"nome":nome})
  c = c + 1

for codigo,item in enumerate(lista10):
  print(codigo,'-',item['nome'])

# CRUD COM REPETICAO

print("Cadastro de mapas Counter Strike")
lista = []
op = ''

while op != 0:

  print()
  print("Lista de mapas competitivos")
# listagem
  c = 0
  while c < len(lista):
    print(c," ",lista[c])
    c = c + 1

  print()
  print("*******************")
  print("1 - cadastro")
  print("2 - atualizacao")
  print("3 - deletar")
  print("0 - sair")
  print("*******************")


  op = int(input("Digite a opcao: "))
  if op == 1:
    mapa = input("Digite o mapa: ")
    lista.append(mapa)
  elif op == 2:
    codigo = int (input("Digite o codigo do mapa: "))
    lista[codigo] = input("Trocar map_pool competitivo: ")
  elif op == 3:
    codigo = int (input("Digite o codigo do mapa"))
    lista[codigo]
    print(lista.pop(lista[codigo]," - Excluido com sucesso"))

# CRUD dicionario

print("Cadastro mapas Counter Strike")

lista0 = []
di_mapas = {"nome_mapa":"","jogador":""}
op = ''
ind = ''
while op != 0:

  print()
  print("*******************")
  print("1 - cadastro")
  print("2 - atualizacao")
  print("3 - deletar")
  print("0 - sair")
  print("*******************")

  op = int(input("Digite a opcao: "))
  if op == 1:
    mapa = input("Digite o mapa: ")
    time = input("Digite o time: ")

    di_mapas["jogador"] = time
    di_mapas["nome_mapa"] = mapa
    lista0.append(di_mapas)


  elif op == 2:
    print()
    print(lista0)
    print()
    ind = int(input("Digite a posicao: "))
    mapa = input("Digite o novo mapa: ")
    lista0[ind]["nome_mapa"] = mapa

for mapa in lista0:
  print(lista0)

print("cadastro alunos")
lista = []
op = ''

while op != 0:
  print("1 - cadastro")
  print("2 - atualizacao")
  print("3 - deletar")
  print("0 - sair")

  op = int(input("Digite a opcao: "))

  if op == 1:
    nome = input("Digite o nome: ")
    idade = int(input("Digite a idade: "))
    cpf = input("Digite o cpf")
    di = {"nome":nome,"idade":idade,"cpf":cpf}

  elif op == 2:
    codigo = int(input("Digite o codigo: "))
    lista[codigo]['nome'] = input("Digite o novo nome: ")
    lista[codigo]['idade'] = int(input("Digite a nova idade: "))
    lista[codigo]['cpf'] = input("Digite o novo cpf: ")
  elif op == 3:
    codigo = int(input("Digite o codigo para alterar"))
    print(lista.pop(codigo)['nome'],"removido com sucesso")

  elif op == 4:
    for item in lista:
      print("codigo",codigo)
      print("nome",item['nome'])
      print("idade",item['idade'])
      print("cpf",item['cpf'])
      print()

def inpput():
  return input("Digite um informação")

def retunNumber():
  return 10

def teste():
  print("teste")

retunNumber()

# parametros

def soma(num1,num2):
  res = num1 + num2
  print(res)

soma(10,10)
soma(20,10)
soma(30,10)

def soma(num1,num2):
  res = num1 + num2
  print(res)

def soma1(num1,num2):
  res1 = num1 + num2
  return res1

soma(10,10)
soma(20,10)
soma(30,10)

res1 = soma1
print(soma1)
res = soma
print(soma)

def soma_(num1,num2):
  soma = num1 + num2
  print("**************")
  print()
  print("Resultado: ",soma)
  print()
  print("**************")

def div_(num1,num2):
  div = num1 / num2
  print("**************")
  print()
  print("Resultado: ",div)
  print()
  print("**************")


def mult_(num1,num2):
  mult = num1 * num2
  print("**************")
  print()
  print("Resultado: ",mult)
  print()
  print("**************")

def sub_(num1,num2):
  sub = num1 - num2

  print("**************")
  print()
  print("Resultado: ",sub)
  print()
  print("**************")

op = ''

while op != 0:
  print("1 - Soma")
  print("2 - divisao")
  print("3 - multiplicacao")
  print("4 - subtracao")
  print("0 - FINALIZAR")
  op = int(input("Digite a operação que deseja realizar: "))

  if op == 1:
    print()
    num1 = float(input("Digite o primeiro numero: "))
    num2 = float(input("Digite o segundo numero: "))
    soma_(num1,num2)


  elif op == 2:
      num1 = float(input("Digite o primeiro numero: "))
      num2 = float(input("Digite o divisor: "))
      div_(num1,num2)


  elif op == 3:
    print()
    num1 = float(input("Digite o primeiro numero: "))
    num2 = float(input("Digite o segundo numero: "))
    mult_(num1,num2)

  elif op == 4:
    print()
    num1 = float(input("Digite o primeiro numero: "))
    num2 = float(input("Digite o segundo numero: "))
    sub_(num1,num2)
    op = int(input("Digite a opeação que deseja realizar: "))

  elif op == 0:
    print("Finalizado")

  elif op > 4 or op < 0:
    print()
    print("**Opcao invalida digite novamente**")
    print()

!python calc.py
# as o apelidos para operacoes
# import operacoes as o