# -*- coding: utf-8 -*-
"""aula_12_04_for

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Px_Rlk-5Hq3W7_IIOVTh0voabDDyRRse
"""

for i in [2,3,4,5,6]:
  print(i)

lista = [2,3,4,5,6,7]
for item in lista:
  print(item)

lista = [2,3,4,5,6,7]
for item in lista[::-1]:
  print(item)

# enumerate

lista = [2,3,4,5,6,7]
for c,item in enumerate(lista):
  print((c + 1),'-',item)

# range
for numero in range(10):
  print(numero)
print()
for numero in range(2,10):
  print(numero)
print()
for numero in range(2,10,2):
  print(numero)

# sort - ordenacao

li1 = ['a','b','c','d','e','f','g']
li2 = ['a','b','c','d','e','f','g']

print(li1)
print(li2)

i1.sort()
print(li1)
li1.sort(reverse=False)
print(li1)
li2.sort(reverse=True)
print(li2)

#maior e menor

lista = [2,3,4,5,6,7,8,9,10]

print(min(lista))
print(max(lista))