# -*- coding: utf-8 -*-
"""aula_26_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i2EfG22iKAH6p0n2-H5X6w3C4TIj3sV5
"""

lista = [2,3,4,5,6,7,8,9]

busca = int(input("Digite o numero que deseja procurar: "))

if busca in lista:
  print(lista.index(busca))
else:
  print("O item nao esta na lista")

lista = [2,3,4,5,6,7,8,9]

busca = ''

while busca not in lista:

  busca = int(input("Digite o numero que deseja procurar: "))

  if lista == []:
      print("A lista esta vazia")
      break

  elif busca in lista:
      print(lista.index(busca))
  else:
    print("O item nao esta na lista")

if lista.count(busca) > 0:
  print(lista.index(busca))
else:
  print("O item nao esta na lista")

lista = []
c = 0
adiciona = ''
while c < 8:
  adiciona = int(input("Adicione um item na lista: "))

  if adiciona not in lista:
    lista.append(adiciona)
    c = c + 1
  elif adiciona in lista:
   print("Item ja adicionado")

lista.sort()
print(lista)