# -*- coding: utf-8 -*-
"""aula_12_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiP99FtL97LQfEYnY72wmYhpOatFqL-M
"""

lista = []
c = 0
contador = 0
while c < 8:
  numeros = int(input(f"Digite o {contador + 1} numero: "))
  lista.append(numeros)
  contador += 1
  c = c + 1

numeroBuscado = int(input("Digite o numero buscado: "))

c = 0
encontrado = -1
while c < 8:
  if lista[c] == numeroBuscado:
      encontrado = c
      c = c + 1

if encontrado == -1:
  print("Numero na se econtra no vetor")
else:
  print("O numero se encontra na posicao",encontrado)

lista = []

c = 0
contador = 0
while c < 10:
  numero = int(input(f"Digite o {contador + 1} numero: "))
  lista.append(numero)
  contador +=1

  c = c + 1
print(lista)
c = 0
while c < 5:
    temp = lista[c]
    lista[c] = lista[(9 - c)]
    lista[(9 - c)] = temp
    c = c + 1


print(lista)

# fatiando listas

lista = [20,30,10,50,60,70]

print(lista)

#comeca e aonde termina -1
print(lista[3::])
del(lista[0:5])
print(lista)

#pesquisa
listap = [1,2,3,4,5,6,5]
print(listap.index(4))

#contagem
print(listap.count(5))
if 5 in listap == True:
  print("tem na lista")
else:

#esta presente
  print(5 in listap)

# sort - ordenacao
l1 = ['a','b','c','d','e']
l2 = ['a','b','c','d','e']
l1.sort()
l2.sort(reverse=True)

print(l1)
print(l2)

#invertendo lista
l = [1,2,3,4,5,6,7,8,9]
print(l)
l.reverse()
print(l)