# -*- coding: utf-8 -*-
"""Aula_26_04_for

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6zurPBQV2VnAGXqXa7YruusYsRjgcN8
"""

for i in [2,3,4,5,6]:
  print(i)

lista = [2,3,4,5,6,7,8,9]

for item in lista:
  print(item)

# lista[aonde comeca : aonde termina(a posicao sera o numero colocado -1) : quanto em quanto "anda"(numeros negativos mostra a lista invertida)]

print(lista[0:7:2])

#tupla - lista imutavel
tupa = 2,3,4,5,6,7,8,9
print(tupa)
print(tupa[0])
print(tupa[-1])
print(tupa[0:2])

print(type(tupa))
l = list(tupa)
l[2] = 3
print(l)

fruta = ['maca','banana','melao']
for ind,fruta in enumerate(fruta):
  print((ind + 1),"-",fruta)

lt = tuple(l)
print(lt)

# range
numero = [2,3,4,5,6,7,8,9,10,11,12,13,14,15]
for i in range(9,10,5):
  print(numero)

for numero in range(1,10)
  print(numero)

for numero in range(20,41,2):
  print(numero)

for numero in range(0,201,10):
  print(numero)

for numero in range(50,0,-1):
  print(numero)

lista = list(range(50,0,-1))
print(lista)

# list comprehension

listaC = [pow(numero,2) for numero in range(1,10)]
print(listaC)