# -*- coding: utf-8 -*-
"""Lista_cs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vaVq97Kvfsu30wcr_lyHDMlDRJadgwBg
"""

lista = []
print(lista)

# acessando lista

lista = [10,11,12,14,15,16]

print(lista[0])
lista[1] = 25
print(lista[1])

letras = ['a','b','c','d','e']

print(letras[-1])

#lista de um texto

palavra = 'braganca'

print(palavra[0])

# add elementos

lista = []

lista.append(10)

print(lista)

#add lista com repeticao

op = ''
lista = []
while op != 's':
  n = int(input("Digite um numero: "))
  lista.append(n)
  op = input("Digite a operacao(a = adicionar | s = sair)")

print(lista)

# limpa a lista

print(lista)
lista.clear()
print(lista)

# insert lista

lista0 = ['A','B','C','D','E']
print(lista0)

lista0.insert(0,'F')
print(lista0)

print(lista0[2])
lista0[2] = 2
print(lista0[2])
print(lista0)

# ADICIONANDO E LISTA ELEMENTOS

l = []
c = 0
while c < 4:
  n = int(input("Digite um numero: "))
  l.append(n)
  c = c + 1
print(l)

c = 0
while c < 4:
  print(l[c])

  c = c + 1

# mostrar numero a numero usando outro while

lista = []
c = 0
while c < 6:
  n = int(input("Digite um numero: "))
  lista.append(n)
  c = c + 1

c = 0
soma = 0
while c < 6:
   soma += lista[c]
   c = c + 1
print("A soma total e:",soma)

lista = []
c = 0

while c < 6:
  n = int(input("Digite um numero: "))
  lista.append(n)
  c = c + 1

c = 0
while c < 6:
  if lista[c] >= 0:
    print(lista[c])

  c = c + 1

lista = []
c = 0
contador = 0
soma = 0
media = 0
while c < 6:
  notas = int(input(f"Digite a nota do aluno {contador + 1}: "))
  lista.append(notas)
  soma += notas
  contador +=1
media = soma / contador

  c = c + 1

c = 0
while c < 4:
    if lista[c] < 7:
      print("Alunos abaixo da media")
      print(lista[c])
c = c + 1
print("A media da sala e",media)

lista = []
c = 0
while c < 4:
  n =int(input("Digite uma nota: "))
  lista.append(n)
  c = c + 1

c = 0
soma = 0

while c < 4:
  soma = soma + lista[c]
  c = c +1
media = soma / 4
print(media)

c = 0
n_abaixo = 0
n_acima = 0

while c < 4:
  if lista[c] < media:
    n_abaixo = n_abaixo + 1
  elif lista[c] > media:
    n_acima = n_acima + 1
  c = c + 1

print("Media", media)
print("Numero abaixo: ",n_abaixo)
print("Numero acima: ",n_acima)

# descobrir tamanho

lista = [2,3,4,5]

print(len(lista))

lista = [2,3,4,5,6,7]

print(lista)
del(lista[0])
print(lista)

# C.R.U.D

list_crud = []

# CREATE
list_crud.append(10)
list_crud.append(20)
list_crud.append(35)

# READ

print(list_crud)

# UPDATE

list_crud[1] = 99

print(list_crud)

del(list_crud[2])

print(list_crud)

# POP - EXCLUIR E MOSTRAR

lista = [2,4,5,6]

print(lista.pop(0))
print(lista)

# CRUD COM REPETICAO

print("Cadastro de mapas Counter Strike")
lista = []
op = ''

while op != 0:

  print()
  print("Lista de mapas competitivos")
# listagem
  c = 0
  while c < len(lista):
    print(c," ",lista[c])
    c = c + 1

  print()
  print("*******************")
  print("1 - cadastro")
  print("2 - atualizacao")
  print("3 - deletar")
  print("0 - sair")
  print("*******************")


  op = int(input("Digite a opcao: "))
  if op == 1:
    mapa = input("Digite o mapa: ")
    lista.append(mapa)
  elif op == 2:
    codigo = int (input("Digite o codigo do mapa"))
    lista[codigo] = input("Trocar map_pool competitivo: ")
  elif op == 3:
    codigo = int (input("Digite o codigo do mapa"))
    lista[codigo]
    print(lista.pop(lista[codigo]," - Excluido com sucesso"))